import { batchCache } from '../utils/batch-cache';

const API_BASE = 'https://brainboxinstitute.in/api';

// Helper to map batch attributes for backward compatibility with Edura components
const mapBatchCompat = (batch) => {
  if (!batch) return batch;
  return {
    ...batch,
    _id: batch._id || batch.batch_id,
    previewImage: batch.previewImage || batch.photo || "/images/hero-2.png",
    feeTotal: 0
  };
};

export const fetchBatches = async () => {
  try {
    const batches = await batchCache.getAllBatches();
    return batches.map(mapBatchCompat);
  } catch (error) {
    console.error('Error fetching batches:', error);
    return [];
  }
};

/**
 * Uses batchCache with built-in Levenshtein and Phonetic fuzzy search, paginating local/remote data.
 */
export const fetchBatchesPaginated = async (page = 1, limit = 15, query = '', signal) => {
  try {
    let filteredData = [];
    if (query) {
      // Query the batch cache using its high-fidelity fuzzy search
      const searchResults = await batchCache.search(query, 999999);
      filteredData = searchResults.map(mapBatchCompat);
    } else {
      const allBatches = await batchCache.getAllBatches();
      filteredData = allBatches.map(mapBatchCompat);
    }

    // Paginate
    const startIndex = (page - 1) * limit;
    const endIndex = page * limit;
    const paginatedData = filteredData.slice(startIndex, endIndex);

    return {
      data: paginatedData,
      hasMore: endIndex < filteredData.length,
      nextPage: endIndex < filteredData.length ? page + 1 : null,
      total: filteredData.length
    };
  } catch (error) {
    if (error.name === 'AbortError') {
      throw error;
    }
    console.error('Error fetching paginated batches:', error);
    return {
      data: [],
      hasMore: false,
      nextPage: null,
      total: 0
    };
  }
};

export const fetchBatchDetails = async (batchId, signal) => {
  try {
    const batches = await batchCache.getAllBatches();
    const batch = batches.find(b => b._id === batchId || b.batch_id === batchId);
    return mapBatchCompat(batch) || null;
  } catch (error) {
    console.error('Error fetching batch details:', error);
    return null;
  }
};

/**
 * Connect to Google Gemini API (if VITE_GEMINI_API_KEY is present)
 * or return a detailed simulated response
 */
export const askStudyBuddy = async (query) => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  
  if (apiKey) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `You are Saarthi, an expert AI Doubt Solver for EDURA Ed-Tech platform. Answer this query in simple educational terms, highlighting key concepts: ${query}` }] }]
        })
      });

      if (!response.ok) throw new Error('Gemini API call failed');
      const data = await response.json();
      return data.candidates[0].content.parts[0].text;
    } catch (error) {
      console.error('Gemini API error, falling back to mock response:', error);
    }
  }

  return `Here is a detailed explanation of "${query}". [Simulated Response] In a live environment with VITE_GEMINI_API_KEY, this response is generated by the Google Gemini model to assist you. Keep up the great studying!`;
};

/**
 * Submit Support message. Sends message to Telegram Bot API if credentials exist
 * or simulates success on local console.
 */
export const submitSupportMessage = async (message, adminUsername) => {
  const botToken = import.meta.env.VITE_TELEGRAM_BOT_TOKEN;
  const chatId = import.meta.env.VITE_TELEGRAM_CHAT_ID;

  const textMessage = `🚨 *NEW SUPPORT TICKET* 🚨\n\n*Admin Requested:* ${adminUsername}\n*Message:* ${message}`;

  if (botToken && chatId) {
    try {
      const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          chat_id: chatId,
          text: textMessage,
          parse_mode: 'Markdown'
        })
      });

      if (!response.ok) throw new Error('Telegram Bot API call failed');
      const data = await response.json();
      return { success: true, data };
    } catch (error) {
      console.error('Telegram notification failed:', error);
      return { success: false, error: error.message };
    }
  }

  // Local/mock log fallback
  console.log(`[API MOCK] Support Ticket for ${adminUsername}: "${message}"`);
  await new Promise(resolve => setTimeout(resolve, 800));
  return { success: true, mock: true };
};

/**
 * Fetch Official DPP Quiz Questions dynamically
 */
export const fetchDppQuiz = async () => {
  const url = `https://brainboxinstitute.in/api/dpp-quiz?batchId=698ad3519549b300a5e1cc6a&scheduleId=6a2a696bf4c2a248d05f796b&testId=6a1eccafbba856d03b9a5a08&tag=Start&isFreeTest=false`;
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error('Failed to fetch DPP Quiz from server');
    return await res.json();
  } catch (err) {
    console.error('Error fetching DPP quiz:', err);
    return null;
  }
};

/**
 * Fetch Quiz Solution Videos securely
 */
export const fetchDppSolutionVideo = async () => {
  const url = `https://brainboxinstitute.in/api/test-solution-video?parentId=698ad3519549b300a5e1cc6a&childId=6a310f89446d03abc3c9a7ff&videoId=68603956298ec880cc405ea9&videoUrl=https%3A%2F%2Fd1d34p8vz63oiq.cloudfront.net%2F49bea851-026e-4737-9af0-f8930a2f9ee5%2Fmaster.mpd&url_type=penpencilvdo`;
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error('Failed to fetch DPP Solution Video from server');
    return await res.json();
  } catch (err) {
    console.error('Error fetching DPP Solution video:', err);
    return null;
  }
};
